name: Build QEMU-iOS for Intel Mac

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone qemu-ios repository
        run: |
          git clone https://github.com/devos50/qemu-ios.git
          cd qemu-ios
          git submodule update --init

      - name: Install dependencies and export LD, CPP flags and PKG CONFIG PATH.
        run: |
          sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
          xcode-select -p
          export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"
          export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
          brew install glib ninja pkg-config sdl2 openssl@3 meson
          pip3 install distlib --break-system-packages

      - name: Build qemu-ios and move it to correct folder
        run: |
          cd qemu-ios
          mkdir build
          cd build
          ../configure --target-list=arm-softmmu \
            --extra-cflags=-I/usr/local/opt/openssl@3/include \
            --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto'
          make -j$(sysctl -n hw.logicalcpu)
          cd ..
          sudo mv build ..
          cd ..
          sudo rm -rf qemu-ios

      - name: Zip build folder
        run: zip -r build-macos.zip build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qemu-ios-build-macos
          path: build-macos.zip
